linters-settings:
  goimports:
    simplify: true
  govet:
    check-shadowing: true
linters:
  presets:
    - bugs
    - unused
    - error
    - style
  enable:
    - gosec
    - revive
    - exportloopref
  disable:
    - interfacer # deprecated
    - golint # deprecated
    - scopelint # deprecated
    - tparallel
    - paralleltest
    - godox
    - wrapcheck
